/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f2f149ee-64c0-4971-885a-3a0ac0a79d02",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2B3tXxSDC",
    "aws_user_pools_web_client_id": "16vddrdfa59e5n5l4d6bl4lalt",
    "host": "ayfcr0t3x1f4a-ats.iot.us-east-2.amazonaws.com" ,
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
